networks:
  node-ntwk: {}

volumes:
  node-db-data:
  node-static:

services:
  node-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nodedb
      MYSQL_USER: nodeusr
      MYSQL_PASSWORD: nodepass
    ports:
      - "3306"
    networks:
      - node-ntwk
    volumes:
      - node-db-data:/var/lib/mysql

  node-app:
    build: .
    image: tpdockerimage
    environment:
      - DB_HOST=node-mysql
      - DB_NAME=nodedb
      - DB_USER=nodeusr
      - DB_PASSWORD=nodepass
    networks:
      - node-ntwk
    ports:
      - "3000:3000"
    depends_on:
      - node-mysql
    volumes:
      - node-static:/usr/src/app
    restart: on-failure